apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunes-app-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tunes-app
  template:
    metadata:
      labels:
        app: tunes-app
    spec:
      containers:
      - name: tunes-app
        image: allennyu/tunes-backend:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: tunes-app-service
spec:
  type: LoadBalancer
  selector:
    app: tunes-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080