apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunes-app-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: tunes-app
  template:
    metadata:
      labels:
        app: tunes-app
    spec:
      containers:
      - name: tunes-app
        image: allennyu/tunes-backend:latest
        env:
        - name: APP_HOST
          value: "https://9yhvjhtr7l.execute-api.us-east-1.amazonaws.com/default/prim"
        - name: SPOTIFY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: SPOTIFY_CLIENT_ID
        - name: SPOTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: SPOTIFY_CLIENT_SECRET
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: AWS_ACCESS_KEY
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: AWS_SECRET_KEY
        ports:
        - containerPort: 8080
          name: tunes-http-port
        livenessProbe:
          httpGet:
            path: /live
            port: tunes-http-port
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /ready
            port: tunes-http-port
          initialDelaySeconds: 5
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
  name: tunes-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: tunes-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: tunes-http-port